name: aplikasi_iot
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  fluttertoast: ^8.1.1
  shared_preferences: ^2.0.15
  provider: ^6.0.5
  cupertino_icons: ^1.0.6
  syncfusion_flutter_charts: ^20.2.46 # Menambahkan dependensi Syncfusion
  mqtt_client: ^9.0.0
  flutter_webrtc: ^0.9.21
  permission_handler: ^10.2.0
  web_socket_channel: ^2.1.0
  camera: ^0.10.0+4
  # typed_data: ^1.3.0
  intl: ^0.18.0
  flutter_riverpod: ^2.0.0
  webview_flutter: ^4.0.0
  video_player: ^2.5.0
  camera_web: ^0.3.5
  html: ^0.15.5
  curved_navigation_bar: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/google.png
    - assets/icons/facebook.png
    - assets/icons/battery.png
    - assets/icons/joy.png
    - assets/icons/camera.png
    - assets/icons/maps.png
    - assets/icons/menu.png
    - assets/icons/speedometer.png
    - assets/icons/command.png
    - assets/icons/distance.png
    - assets/icons/firefighter_logo.png
    - assets/icons/api.png
    - assets/icons/gambar_1.png
    - assets/icons/gambar_2.png
    - assets/icons/gambar_3.png
